Repository EveronLife/EveronLife, pull requests merged in 2022-06, with the labels that each got.

#69 Optimise apple model
  assets/model/apple/License.txt
  assets/model/apple/apple.fbx
  assets/model/apple/apple.jpg
  assets/model/apple/apple_BCR.tif
  src/Assets/Items/Food/Apple/Apple.xob
  src/Assets/Items/Food/Apple/Apple.xob.meta
  src/Assets/Items/Food/Apple/Apple_01.fbx
  src/Assets/Items/Food/Apple/Apple_01.txo
  src/Assets/Items/Food/Apple/Apple_01.xob
  src/Assets/Items/Food/Apple/Apple_01.xob.meta
  src/Assets/Items/Food/Apple/Data/Apple.emat
  src/Assets/Items/Food/Apple/Data/Apple.emat.meta
  src/Assets/Items/Food/Apple/Data/Apple_01.edds
  src/Assets/Items/Food/Apple/Data/Apple_01.edds.meta
  src/Assets/Items/Food/Apple/Data/Apple_01.emat
  src/Assets/Items/Food/Apple/Data/Apple_01.emat.meta
  src/Assets/Items/Food/Apple/Data/Apple_01.jpg
  src/Assets/Items/Food/Apple/Data/Apple_BCR.edds
  src/Assets/Items/Food/Apple/Data/Apple_BCR.edds.meta
  src/Assets/Items/Food/Apple/apple.xob
  src/Assets/Items/Food/Apple/apple.xob.meta
  src/Prefabs/Items/Food/Apple.et
Labels: enhancement

#50 Addition of Plum Gathering
  assets/model/plum/License.txt
  assets/model/plum/Plum.fbx
  assets/model/plum/Plum.tif
  src/Assets/Items/Food/Plum/Plum.xob
  src/Assets/Items/Food/Plum/Plum.xob.meta
  src/Assets/Items/Food/Plum/data/Plum.edds
  src/Assets/Items/Food/Plum/data/Plum.edds.meta
  src/Assets/Items/Food/Plum/data/Plum.emat
  src/Assets/Items/Food/Plum/data/Plum.emat.meta
  src/Prefabs/Items/Food/Plum.et
  src/Prefabs/Items/Food/Plum.et.meta
  src/Prefabs/Vegetation/Tree/t_prunus_domestica_2s.et
  src/Prefabs/Vegetation/Tree/t_prunus_domestica_2s.et.meta
Labels: feature

#79 Add Tomatos
  assets/Models/Tomato/Tomato.fbx
  assets/Models/Tomato/Tomato_BCR.tif
  assets/Models/Tomato/Tomato_NMO.tif
  src/Assets/Items/Food/Tomato/Data/Tomato.emat
  src/Assets/Items/Food/Tomato/Data/Tomato.emat.meta
  src/Assets/Items/Food/Tomato/Data/Tomato_BCR.edds
  src/Assets/Items/Food/Tomato/Data/Tomato_BCR.edds.meta
  src/Assets/Items/Food/Tomato/Data/Tomato_BCR.tif
  src/Assets/Items/Food/Tomato/Data/Tomato_NMO.edds
  src/Assets/Items/Food/Tomato/Data/Tomato_NMO.edds.meta
  src/Assets/Items/Food/Tomato/Data/Tomato_NMO.tif
  src/Assets/Items/Food/Tomato/Tomato.fbx
  src/Assets/Items/Food/Tomato/Tomato.txo
  src/Assets/Items/Food/Tomato/Tomato.xob
  src/Assets/Items/Food/Tomato/Tomato.xob.meta
  src/Prefabs/Items/Food/Tomato.et
  src/Prefabs/Items/Food/Tomato.et.meta
  src/Worlds/DebugWorld/DebugWorld.ent
  src/Worlds/DebugWorld/DebugWorld_Terrain.layer
  src/Worlds/DebugWorld/DebugWorld_TomatoChain.layer
Labels: feature

#80 Remove assets directory
  assets/Models/TitleImagePoster/titleposter.blend
  assets/Models/Tomato/Tomato.fbx
  assets/Models/Tomato/Tomato_BCR.tif
  assets/Models/Tomato/Tomato_NMO.tif
  src/Assets/Items/Food/Apple/Apple.fbx
  src/Assets/Items/Food/Apple/Apple.txo
  src/Assets/Items/Food/Apple/Data/Apple_BCR.tif
  src/Assets/Items/Food/Plum/License.txt
  src/Assets/Items/Food/Plum/Plum.fbx
  src/Assets/Items/Food/Plum/Plum.txo
  src/Assets/Items/Food/Plum/Plum.xob
  src/Assets/Items/Food/Plum/Plum.xob.meta
  src/Assets/Items/Food/Plum/data/Plum.edds.meta
  src/Assets/Items/Food/Plum/data/Plum.tif
Labels: enhancement

#75 Add vehicle license plate prototype
  src/Assets/Vehicles/LicensePlate/LicensePlate.fbx
  src/Assets/Vehicles/LicensePlate/LicensePlate.xob
  src/Assets/Vehicles/LicensePlate/LicensePlate.xob.meta
  src/Assets/Vehicles/LicensePlate/data/LicensePlateMaterial.emat
  src/Assets/Vehicles/LicensePlate/data/LicensePlateMaterial.emat.meta
  src/Assets/Vehicles/LicensePlate/data/Material.emat
  src/Assets/Vehicles/LicensePlate/data/Material.emat.meta
  src/Assets/Vehicles/LicensePlate/data/PIPMaterial.emat
  src/Assets/Vehicles/LicensePlate/data/PIPMaterial.emat.meta
  src/Configs/Vehicles/VehicleSettings.conf
  src/Configs/Vehicles/VehicleSettings.conf.meta
  src/Prefabs/Vehicles/Core/Vehicle_Base.et
  src/Prefabs/Vehicles/Core/Vehicle_Base.et.meta
  src/Prefabs/Vehicles/LicensePlate/LicensePlate.et
  src/Prefabs/Vehicles/LicensePlate/LicensePlate.et.meta
  src/Scripts/Game/Components/Vehicle/EL_LicensePlateManagerComponent.c
  src/Scripts/Game/Configs/EL_VehicleSettings.c
  src/Scripts/Game/Features/LicensePlate/EL_LicensePlateGeneratorBase.c
  src/Scripts/Game/Features/LicensePlate/EL_LicensePlateGeneratorGeneric.c
  src/Scripts/Game/Features/LicensePlate/EL_LicensePlateManager.c
  src/Scripts/Game/Vehicle/EL_LicensePlateEntity.c
  src/UI/Layouts/LicensePlate/EL_LicensePlatePlate.layout
  src/UI/Layouts/LicensePlate/EL_LicensePlatePlate.layout.meta
  src/UI/Layouts/LicensePlate/LicensePlate.layout
  src/UI/Layouts/LicensePlate/LicensePlate.layout.meta
Labels: feature

#111 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation

#102 Update Feature/Improve gathering with more parameters
  src/Scripts/Game/Features/Gathering/EL_GatherAction.c
Labels: feature

#88 feature/axe_for_logging
  src/Assets/Tools/Axe/Axe.fbx
  src/Assets/Tools/Axe/Axe.txo
  src/Assets/Tools/Axe/Axe.xob
  src/Assets/Tools/Axe/Axe.xob.meta
  src/Assets/Tools/Axe/Data/Axe.emat
  src/Assets/Tools/Axe/Data/Axe.emat.meta
  src/Assets/Tools/Axe/Data/Axe_BCR.edds
  src/Assets/Tools/Axe/Data/Axe_BCR.edds.meta
  src/Assets/Tools/Axe/Data/Axe_BCR.tif
  src/Assets/Tools/Axe/Licence.txt
  src/Prefabs/Tools/Axe/Axe.et
  src/Prefabs/Tools/Axe/Axe.et.meta
  src/Prefabs/Tools/Tool_Base.et
  src/Prefabs/Tools/Tool_Base.et.meta
  src/Worlds/DebugWorld/DebugWorld.ent
  src/Worlds/DebugWorld/DebugWorld_LoggingChain.layer
Labels: feature

#95 Add water bottle item
  src/Assets/Items/Drinks/WaterBottle/Bottle.fbx
  src/Assets/Items/Drinks/WaterBottle/Bottle.txo
  src/Assets/Items/Drinks/WaterBottle/Bottle.xob
  src/Assets/Items/Drinks/WaterBottle/Bottle.xob.meta
  src/Assets/Items/Drinks/WaterBottle/Data/Bottle.emat
  src/Assets/Items/Drinks/WaterBottle/Data/Bottle.emat.meta
  src/Assets/Items/Drinks/WaterBottle/Data/Bottle_BCR.edds
  src/Assets/Items/Drinks/WaterBottle/Data/Bottle_BCR.edds.meta
  src/Assets/Items/Drinks/WaterBottle/Data/Bottle_BCR.tif
  src/Assets/Items/Drinks/WaterBottle/Data/Bottle_NMO.edds
  src/Assets/Items/Drinks/WaterBottle/Data/Bottle_NMO.edds.meta
  src/Assets/Items/Drinks/WaterBottle/Data/Bottle_NMO.tif
  src/Prefabs/Items/Drinks/WaterBottle.et
  src/Prefabs/Items/Drinks/WaterBottle.et.meta
  src/Worlds/DebugWorld/DebugWorld_default.layer
Labels: feature
